# Generated by Django 3.0.6 on 2020-06-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotYoutube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vedio', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('thumb', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'accepted'), (3, 'rejected')], default=1)),
            ],
        ),
    ]
