# Generated by Django 3.0.4 on 2020-05-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('dead', models.BigIntegerField(default=0)),
                ('sick', models.BigIntegerField(default=0)),
                ('recovered', models.BigIntegerField(default=0)),
                ('infected', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('p', 'pending'), ('a', 'approved'), ('r', 'rejected')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalZone',
            fields=[
                ('zone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zone.Zone')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('AU', 'South America')], max_length=2)),
            ],
            bases=('zone.zone',),
        ),
        migrations.CreateModel(
            name='NationalZone',
            fields=[
                ('zone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zone.Zone')),
                ('remarque', models.CharField(blank=True, max_length=500, null=True)),
                ('radius', models.FloatField()),
                ('is_risky', models.BooleanField(default=False)),
            ],
            bases=('zone.zone',),
        ),
    ]
