# Generated by Django 3.0.4 on 2020-05-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalzone',
            name='radius',
        ),
    ]
