# Generated by Django 3.0.6 on 2020-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_remove_nationalzone_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='y',
            field=models.FloatField(),
        ),
    ]
