# Generated by Django 3.0.6 on 2020-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_auto_20200605_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalzone',
            name='continent',
            field=models.CharField(blank=True, choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('AU', 'South America')], max_length=2, null=True),
        ),
    ]
