# Generated by Django 3.0.6 on 2020-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_auto_20200606_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalzone',
            name='carrier',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
