# Generated by Django 3.0.6 on 2020-06-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wilaya',
            old_name='name',
            new_name='nom',
        ),
    ]
