# Generated by Django 3.0.4 on 2020-05-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('user', models.FileField(upload_to='', verbose_name='user.User')),
            ],
        ),
    ]
