# Generated by Django 3.0.4 on 2020-05-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(default=None, max_length=500, upload_to='attachment')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'accepted'), (3, 'rejected')], default=1)),
            ],
        ),
    ]
