# Generated by Django 3.0.6 on 2020-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuspectedCase', '0003_auto_20200603_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectedcase',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectedcase',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
